version: "3.2"
networks:
  nw:
volumes:
  gitlab_logs:
  gitlab_data:
  jenkins_data:
  sonardb_data:
  nexus_data:
  
services:
  gitlab:
    image: gitlab/gitlab-ce:13.4.1-ce.0
    restart: "no"
    networks:
      - nw
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://docker.vm/gitlab/'
        web_server['username'] = 'git' 
        web_server['group'] = 'git'
    ports:
      - "10080:80"
      - "10443:443"
      - "10022:22"
    volumes:
      - ${PWD}/config/gitlab:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
      
  jenkins:
    image: jenkins/jenkins:2.235.1-lts-slim
    privileged: true
    restart: "no"
    ports:
      - "9080:8080"
      - "50000:50000"
    networks:
      - nw
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/jvm:/usr/lib/jvm
    environment:
      - JVM_OPTS=-Xmx1024m -Xms1024m -XX:MaxPermSize=1024m
      - JENKINS_OPTS="--prefix=/jenkins"
      - NEXUS_PORT=8081
      
  nexus:
    image: sonatype/nexus3:3.24.0
    restart: "unless-stopped"
    ports:
      - "9091:8081"
    networks:
      - nw
    volumes:
      - nexus_data:/nexus-data
    environment:
      - JVM_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=256m
      - NEXUS_CONTEXT=nexus
      
  sonarqube:
    image: sonarqube:8.3.1-community
    command: -Dsonar.web.context=/sonarqube
    restart: "unless-stopped"
    ports:
     - "9000:9000"
     - "9092:9092"
    networks:
      - nw
    environment:
     - JVM_OPTS=-Xmx1024m -Xms1024 -XX:MaxPermSize=1024m
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=${PASSWORD_SONAR}
      
  sonardb:
    image: postgres:9.6.18-alpine
    networks:
      - nw
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=${PASSWORD_SONAR}
      - POSTGRES_DB=sonar
    volumes:
      - sonardb_data:/var/lib/postgresql/data
